apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:14.3
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_PASSWORD
              value: "kubepwd"
            - name: POSTGRES_USER
              value: "kubeusr"
            - name: POSTGRES_DB
              value: "kubedb"

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    app: postgres
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-news
spec:
  replicas: 3
  selector:
    matchLabels:
      app: kubenews
  template:
    metadata:
      labels:
        app: kubenews
    spec:
      containers:
        - name: kubenews
          image: fmagven/kube-news:v2
          env:
            - name: DB_DATABASE
              value: "kubedb"
            - name: DB_USERNAME
              value: "kubeusr"
            - name: DB_PASSWORD
              value: "kubepwd"
            - name: DB_HOST
              value: "postgres"

---
apiVersion: v1
kind: Service
metadata:
  name: kube-news
spec:
  selector:
    app: kubenews
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30000
  type: NodePort
